### ISSUE TITLE
Modded game not launching

### ISSUE THREAD

**Issue by TheSphess** [teddybear082/CrueltySquadVR-Modloader#16]
After installing the mod it gives me this error:
![image](https://github.com/teddybear082/CrueltySquadVR-Modloader/assets/47431600/8f200bd5-45d0-48f5-82b8-5759cf6743bc)
I did everything right, following the instructions step by step, multiple times.
Tried it on the latest steam version. (July 3)

**Comment by teddybear082** [comment]
I’m not sure unfortunately I’m not able to test on the newest version of the game that just came out today (which also upgraded the engine to Godot 3.5.2 beyond my own upgrade of the engine version (3.4) for another week or so when I get back to my computer.  But it’s a good chance the newest upgrade (which is unexpected since the dev hadn’t worked on the game for over a year when I first made the mod) broke the VR mod.  Sorry. 

 If I can fix it I will when I can but it’s probably not something you are doing wrong.

**Comment by TheSphess** [comment]
No problem, thanks for the reply!

**Comment by teddybear082** [comment]
So, today I tried out all the quick hacks I had hoped would work to get at least some version of the VR mod up and running and unfortunately none worked.  Sorry.  Looks like it will take significant work to get the VR mod up and running again.  No timetable.  I posted an announcement but will also leave this up here so people can see.  If you look on the main page you will see there's this steam depo downloader thing where maybe you can downgrade your game back to the version before July 2023 but I haven't tried it myself yet.

**Comment by TheSphess** [comment]
That's unfortunate... thanks, I'll try downgrading the game and see if it works.

**Comment by teddybear082** [comment]
Actually give me a few days.  I made some progress tonight taking a new approach and have VR working for the newest version of the game in the Godot editor at least.  Have to test tomorrow in the modded game and see what else breaks but I think I may have found the offending code that was breaking the mod.

**Comment by teddybear082** [comment]
Hi can you please try completely deleting the vr mod folders, deleting the cruelty squad install and all files left in the cruelty squad install that were put there by the last VR modloader, reinstall Cruelty Squad, then use V.1.2 of the VR mod (found here: https://github.com/teddybear082/CrueltySquadVR-Modloader/releases), installing from scratch, and let me know if it works for you?  This should work with the July 2023 version of the game.  I tested it on my end but it would help to have someone else confirm before I close this issue.  Thank you!

**Comment by TheSphess** [comment]
It works! Thank you!
