### ISSUE TITLE
Game Runs in Window Showing VR View Without Giving VR View in Headset

### ISSUE THREAD

**Issue by AllenEtcetera** [teddybear082/CrueltySquadVR-Modloader#19]
I tried every release, I'm using SteamVR with Quest 2 via Link Cable. It runs in window showing VR view with full tracking, but it doesn't actually put the view on the headset.

**Comment by teddybear082** [comment]
Hi there.  Only use the most recent release.  Two things, (1) check Steam settings for the game and make sure desktop theatre option is deactivated; (2) check which “OpenXR runtime” is active, SteamVR or Oculus.  In each software you can set theirs to default.  Try one then the other.  If that still doesn’t work then I think there’s a log I can get you to share.

**Comment by Sludge-Friend** [comment]
Hello again! I discovered what the issue was. The oculus software had set itself as the opener for OpenXR instead of SteamVR. Changing the OpenXR manager to SteamVR fixed the issue. Thank you for reaching out, and thank you for this excellent mod!
