### ISSUE TITLE
Bugs and Notes

### ISSUE THREAD

**Issue by Distant075** [teddybear082/CrueltySquadVR-Modloader#3]
Played through the whole game Trauma% while Cursed (excluding Idiot Party) and have found these issues so far

Loadout on all levels but Archon Grid and CSHQ:
Stock Weapons (Pistol/SMG)
Life Sensor
Stealth Suit
Grappendix
Funkgrunters

Toxic Crisis drains health much faster than normal, but ends up draining the same amount.
Target icon rotates with the player's head. (Only saw it happen once on Idiot Party)
Lighting of the area affects menus such as the death window, which makes it hard to see in some scenarios (notably Darkworld)
Psychos/Psykers effect lags the game (maybe the only way to handle the effect?)
You cannot crouch under zombie attacks
The green reticle on suppressed weapons sometimes inverts position(?) when on the skybox, very hard to describe
Reload bar showing whenever weapon is near hip regardless of whether grip is held (intentional?)
Funkgrunter goo appears where you are aiming, not below you
Funkgrunters can only be used once instead of twice, and the sound to use them can be played infinitely
All fog is missing
Infinite walljumps
Kicking is inconsistant, sometimes you have to look at specific angles, sometimes you can't hit it at all
Enemies seem to not react to damage from much shorter distances
Some enemies are placed within the ground (Androgen Assault: enemy before first bouncy castle, Alpine Hospitality: enemy in back right room, falls through ground to 1st floor)
Some surfaces are solid when they are supposed to be passed through (Light rays in Androgen & Idiot Party, liquid roof in Casino Catastrophe)
Above issue causes Idiot Party to be incompletable
The grappendix can give bursts of sudden momentum leading to awkward fall damage deaths, even with the reduced fall damage
Softlock when leaving Miner's Miracle, stuck on "Next Mission" while the Handler talks
Some interactables, such as the book in the beginning of Trauma Loop, are extremely hard to press
Walljumping can sometimes make you land, killing you from fall damage
Frequent crashes, though the exact causes are definitely vague

I'll have a video up in the next few days showing off some of these issues as well as a general playthrough.

**Comment by teddybear082** [comment]
Thank you!

**Comment by Distant075** [comment]
https://youtu.be/83OVn4lykVA

Here's the unlisted video for the bugs, I'll keep it off my public uploads, simply because I don't want to make it seem like I haven't been enjoying the mod.

**Comment by SpencerBinXia** [comment]
The enemy reaction issue should just be due to having the NPC hack enabled, no? When you disable it their AI seems like vanilla.

**Comment by teddybear082** [comment]
I'm going to keep track of bug fixes as I make them at issue #4 , FYI.  Thanks again for all the help, both of you.

**Comment by SpencerBinXia** [comment]
hm, even with AI NPC hack off I can see that sometimes the AI is stuck not reacting like they would be in the regular game. it seems very minor though, for the most part the AI is much better with the hack off then on.

**Comment by teddybear082** [comment]
Outside of the hack code I have not touched AI handling.  One guess could be that the player is more easily “seen” by the AI in flatscreen mode not because of code changes but because of the position of the player and player collider at any particular time.

But you can see the only files I have changed relating to enemies are the New_Grunt (but only to check whether a player instance is valid to prevent crashing on levels that have the second person player view) and enemy handler (only to create and add the code to report into an NPC group and add the detection area).

**Comment by teddybear082** [comment]
Closing this thread and will create a "known issues" thread with things I don't plan on changing right now for release 1.0. I also found out why the NPCs were still not totally performing correctly with hack off. I wasn't de-activating the hack on player area signals. Thanks for all the help!
