### ISSUE TITLE
Squeezing grip at the start of the level quits out.

### ISSUE THREAD

**Issue by PsYchitOut** [teddybear082/CrueltySquadVR-Modloader#8]
Hey there. Love the work you've done with the mod. I was surprised how feature complete it is. Good to see  this mutant abomination of a game getting some real love.

  I however immediately ran into a glaring issue while playing via Steam VR on my Index. For some reason if I close my hand around the grip of my primary hand within about 5 seconds of starting a level, it exit's the level and backs out to the select menu. It's a simple problem that my stupid reflexes make a lot worse than it should. Even knowing the glitch I still instinctively close my hand around the controller the second I see the gun appear.

**Comment by teddybear082** [comment]
#Hi thanks for your thoughts and reporting!  Is this just in the HQ level or all levels? In the HQ level if you are facing the door when you boot up, pressing grip will "enter the elevator to the HQ" (the imaginary one that the doors are for) and go back to the main menu.  The reason the grip button would do this is that it is also the use button so you are "using" the doors to exit the HQ.  If it's in the other levels let me know.

@PsYchitOut

**Comment by PsYchitOut** [comment]
You know what, You might be right. Cause I tried it on Paradise, where it just spawns you in the middle of the road, and nothing happened. Little embarrassing... but tbf, It just triggers so fast I had trouble figuring out what was going on. Like if I'm holding the grip as I load in HQ I'm bumped back to level select before it's even finished loading in lol. Not to mention the way your 'use' function decides to lock on to objects is a little... Over enthusiastic, which is normally a good thing.

I'll make sure to close this. But I'll def. let you know if I find any other weirdness. You know more than what's already there

**Comment by teddybear082** [comment]
Thanks!! I used to think the same thing, wondering why I was jumping out of the level, so that’s why I suspected that.  No worries, always feel free to report!
