### ISSUE TITLE
Audio does not follow headset orientation

### ISSUE THREAD

**Issue by Whaphil** [teddybear082/CrueltySquadVR-Modloader#9]
Headset: Valve Index
Platform: Windows 11 Insider Preview 10.0.22624.1391
Crus Version: Nov14-2021 (Current newest version)
CSVR Version: Mediafire download 21.03.2023

When turning IRL, the audio does not seem to follow the player
When turning Ingame, it does

If any adittional information is needed I am happy to help

**Comment by teddybear082** [comment]
Thank you I will look into this.

**Comment by teddybear082** [comment]
Hi thank you for reporting this, I fixed this now, the fix will be in the 1.1 release.
